name: 'Conveyor-CLI: CI'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  GRYPE_MATCH_GOLANG_USING_CPES: false
  # Personal Access Token  
  CONVEYOR_PROVIDER_TOKEN: "$CONVEYOR_PROVIDER_TOKEN" 
  CONVEYOR_STORAGE_TOKEN: "$CONVEYOR_STORAGE_TOKEN"
  CONVEYOR_STORAGE_ACCOUNT_NAME: "$CONVEYOR_STORAGE_ACCOUNT_NAME"
  CONVEYOR_STORAGE_CONTAINER_NAME: "$CONVEYOR_STORAGE_CONTAINER_NAME" 
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  sbom-stage:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        
        - name: Set up Go
          uses: actions/setup-go@v3
          with:
            go-version-file: go.mod
            cache: true
        
        - name: Build
          run: go run mage.go build
        
        - name: Create SBOM
          uses: anchore/sbom-action@v0
          with:
            format: spdx-json
            output-file: "${{ github.event.repository.name }}-sbom.spdx.json"
        
        - name: Scan SBOM
          id: scan
          uses: anchore/scan-action@v3
          with:
            sbom: "${{ github.event.repository.name }}-sbom.spdx.json"
            output-format: json
            fail-build: high
            severity-cutoff: high

        - name: Upload Artifacts
          uses: actions/upload-artifact@v3
          with:
            name: sbom-stage
            path: |
              /tmp/sbom-action-*/*

  conveyor:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        
        - name: Set up Go
          uses: actions/setup-go@v3
          with:
            go-version: '>=1.19'
        
        - name: Get Conveyor
          run: go install github.com/MChorfa/conveyor-cli@v0.0.2-alpha

        - name: Run Conveyor
          run: |
            conveyor-cli conveyor \
            --commit-hash "$GITHUB_SHA" \
            --owner-name "$GITHUB_REPOSITORY_OWNER" \
            --pipeline-id $GITHUB_RUN_ID \
            --project-id $GITHUB_REPOSITORY_ID \
            --project-name "conveyor-cli" \
            --job-name sbom-stage \
            --provider-api-url "https://api.github.com" \
            --provider-token "${GITHUB_TOKEN}" \
            --provider-type "github" \
            --ref-name "$GITHUB_REF_NAME" \
            --storage-token "${CONVEYOR_STORAGE_TOKEN}" \
            --storage-type "azure" \
            --storage-account-name "${CONVEYOR_STORAGE_ACCOUNT_NAME}" \
            --storage-container-name "${CONVEYOR_STORAGE_CONTAINER_NAME}"