name: 'Conveyor-CLI: CI'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  sbom-stage:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        
        - name: Set up Go
          uses: actions/setup-go@v3
          with:
            go-version-file: go.mod
            cache: true
        
        - name: build
          run: go run mage.go build
        
        - name: Create SBOM
          uses: anchore/sbom-action@v0
          with:
            format: spdx-json
            output-file: "${{ github.event.repository.name }}-sbom.spdx.json"
        
        - name: Scan SBOM
          id: scan
          uses: anchore/scan-action@v3
          with:
            sbom: "${{ github.event.repository.name }}-sbom.spdx.json"

        - name: upload Anchore scan json report
          uses: github/codeql-action/upload-json@v2
          with:
            json_file: ${{ steps.scan.outputs.json }}
        
        - uses: actions/upload-artifact@v3
          with:
            name: sbom-stage
            path: |
              "${{ github.event.repository.name }}-sbom.spdx.json"


            
